data:
  list_run_hour: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 23] # list of input hours for inference
  save_gifs: true
  save_gribs: false
  #args forwarded (linked) to model
  dataset_name: titan_aro_arp
  num_input_steps: 1
  num_pred_steps_train: 1
  num_pred_steps_val_test: 1
  batch_size: 2

  #other args
  num_workers: 10
  prefetch_factor: null
  pin_memory: False
  dataset_conf:
    periods:
      train:
        start: 20230901
        end: 20231031
        obs_step: 3600
      valid:
        start: 20231101
        end: 20231114
        obs_step: 3600
        obs_step_btw_t0: 3600
      test:
        start: 20231117
        end: 20231117
        obs_step: 3600
        obs_step_btw_t0: 3600
    grid:
      name: PAAROME_1S40
      border_size: 0
      subdomain: [100, 612, 240, 880]
      proj_name: PlateCarree
      projection_kwargs: {}
    settings:
      standardize: true
      file_format: npy
    params:
      aro_tp:
        levels: [0]
        kind: input_output
      aro_u10:
        levels: [10]
        kind: input_output
      aro_v10:
        levels: [10]
        kind: input_output